apiVersion: apps/v1
kind: Deployment
metadata:
  name: telcocloud-network-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telcocloud-network
  template:
    metadata:
      labels:
        app: telcocloud-network
    spec:
      containers:
      - name: network-app
        image: telcocloud-network-app
        imagePullPolicy: Never
        ports:
        - containerPort: 80
