apiVersion: v1
kind: Service
metadata:
  name: telcocloud-network-service
spec:
  type: NodePort
  selector:
    app: telcocloud-network
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 9090
