apiVersion: v1
kind: Service
metadata:
  name: telcocloud-network-service
spec:
  type: NodePort
  selector:
    app: telcocloud-network
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30909
