- name: Configure TelcoCloud Node
  hosts: telcocloud
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - curl
          - docker.io
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install k3s using Docker runtime
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--docker" sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for Kubernetes to be ready
      shell: |
        until kubectl get nodes; do
          sleep 5
        done
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Fix kubeconfig permissions
      file:
        path: /etc/rancher/k3s/k3s.yaml
        owner: ubuntu
        group: ubuntu
        mode: "0644"
    - name: Copy application files
      copy:
        src: ../app/
        dest: /home/ubuntu/app/
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Copy Kubernetes manifests
      copy:
        src: ../k8s/
        dest: /home/ubuntu/K8s/
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Copy deploy script
      copy:
        src: ../deploy.sh
        dest: /home/ubuntu/deploy.sh
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Verify Kubernetes node
      shell: kubectl get nodes
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      register: k8s_status

    - debug:
        var: k8s_status.stdout
